name: boda
channels:
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.7
  - pytorch=1.7
  - torchvision=0.8
  - cudatoolkit=10.2
  - numpy
  - cython
  - flake8
  # - pip:
    # - pycocotools
    # - opencv-python